# Generated by Django 3.2.6 on 2021-10-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='short_intro',
        ),
    ]
