# Generated by Django 3.2.6 on 2021-08-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='creditrating',
            field=models.IntegerField(),
        ),
    ]
