# Generated by Django 3.2.6 on 2021-08-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0003_branch_loanagent_loangiven_loaninfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanGiven',
        ),
    ]
