# Generated by Django 3.2.6 on 2021-10-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0005_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
